export const primaryBc : string = '#e8eaf6'; // indigo lighten-5 background background background
export const primaryText : string = '#1A237E'; // indigo darken-4  text text border color text
export const lightText : string = '#ede7f6'; // deep-purple lighten-5 text
export const mainShadows : string = '#4a148c'; // purple darken-4 outline shadow
export const secondaryBc : string = '#9575cd'; // deep-purple lighten-2 background
export const secondaryLightBc : string = '#ba68c8'; // purple lighten-2 background
export const secondaryLightLightBc : string = '#e1bee7'; // purple lighten-4 background
export const secondaryIcon : string = '#512da8'; // deep-purple accent-4 icon;
export const secondaryDarkenIcon : string = '#3949ab'; // indigo darken-1 hover icon
export const primaryIcon : string = '#757575'; // grey darken-1 iconsmenu
export const secondaryText : string = '#424242'; // grey darken-3 iconsactive text
export const lightAccentText : string = '#fce4ec'; // pink lighten-5 textlink
export const lightAccentLink : string = '#ffccbc'; // deep-orange lighten-4 textactivelink
export const secondaryDText : string = '#212121'; // grey darken-4 text
export const secondaryLText : string = '#616161'; // grey darken-2 text
export const accentRedText : string = '#d32f2f'; // red darken-2 textImportant
export const overlayColor : string = '#e0e0e0'; // grey lighten-2 overlay
export const white : string = '#ffffff';
export const topBcModalGradient : string = 'rgba(208,131,206,1) 0%';
export const middleBcModalGradient : string = 'rgba(208,131,206,1) 0%';
export const bottomBcModalGradient : string = 'rgba(208,131,206,1) 0%';
export const topBcGradient : string = 'rgba(94,73,133,1) 0%';
export const middleBcGradient : string = 'rgba(194,128,210,1) 70%';
export const bottomBcGradient : string = 'rgba(236,231,236,1) 100%';
